#!/usr/bin/env python3
"""
MCP Toolkit CLI - Project Templates
"""

import json

TEMPLATES = {
    'basic': {
        'description': 'Basic MCP server with essential tools',
        'languages': ['python', 'typescript', 'javascript'],
        'features': ['hello_world', 'echo', 'calculator']
    },
    'api': {
        'description': 'API wrapper MCP server for external services',
        'languages': ['python', 'typescript'],
        'features': ['http_client', 'auth', 'rate_limiting']
    },
    'data': {
        'description': 'Data processing MCP server',
        'languages': ['python'],
        'features': ['csv_parser', 'json_transform', 'validator']
    },
    'ai': {
        'description': 'AI/LLM integration MCP server',
        'languages': ['python', 'typescript'],
        'features': ['prompt_template', 'chain_builder', 'model_router']
    }
}


def get_template_files(template, language, project_name, features=None):
    """Get template files for project generation"""
    features = features or []
    
    if language == 'python':
        return _get_python_files(template, project_name, features)
    elif language == 'typescript':
        return _get_typescript_files(template, project_name, features)
    elif language == 'javascript':
        return _get_javascript_files(template, project_name, features)
    else:
        return _get_python_files(template, project_name, features)


def _get_python_files(template, project_name, features):
    """Generate Python template files"""
    
    # Server file
    server_py = f'''#!/usr/bin/env python3
"""
{project_name} - MCP Server
Generated by MCP Toolkit CLI
"""

import json
import sys
import os
from typing import Dict, List, Any, Optional


class {project_name.replace('-', '_').title().replace('_', '')}Server:
    """MCP Server Implementation"""
    
    def __init__(self):
        self.name = "{project_name}"
        self.version = "1.0.0"
        self.tools = self._register_tools()
    
    def _register_tools(self) -> List[Dict[str, Any]]:
        """Register available tools"""
        tools = [
            {{
                "name": "hello_world",
                "description": "Say hello to the world",
                "parameters": {{
                    "type": "object",
                    "properties": {{
                        "name": {{
                            "type": "string",
                            "description": "Name to greet"
                        }}
                    }}
                }}
            }},
            {{
                "name": "echo",
                "description": "Echo back the input message",
                "parameters": {{
                    "type": "object",
                    "properties": {{
                        "message": {{
                            "type": "string",
                            "description": "Message to echo"
                        }}
                    }},
                    "required": ["message"]
                }}
            }},
            {{
                "name": "calculator",
                "description": "Perform basic calculations",
                "parameters": {{
                    "type": "object",
                    "properties": {{
                        "operation": {{
                            "type": "string",
                            "enum": ["add", "subtract", "multiply", "divide"],
                            "description": "Math operation"
                        }},
                        "a": {{
                            "type": "number",
                            "description": "First operand"
                        }},
                        "b": {{
                            "type": "number",
                            "description": "Second operand"
                        }}
                    }},
                    "required": ["operation", "a", "b"]
                }}
            }}
        ]
        
        # Add feature-specific tools
        if 'auth' in {features}:
            tools.append({{
                "name": "authenticate",
                "description": "Authenticate a user",
                "parameters": {{
                    "type": "object",
                    "properties": {{
                        "token": {{
                            "type": "string",
                            "description": "Auth token"
                        }}
                    }},
                    "required": ["token"]
                }}
            }})
        
        if 'logging' in {features}:
            tools.append({{
                "name": "get_logs",
                "description": "Retrieve server logs",
                "parameters": {{
                    "type": "object",
                    "properties": {{
                        "level": {{
                            "type": "string",
                            "enum": ["info", "warn", "error", "debug"],
                            "default": "info"
                        }},
                        "limit": {{
                            "type": "integer",
                            "default": 100
                        }}
                    }}
                }}
            }})
        
        return tools
    
    def call_tool(self, tool_name: str, params: Dict[str, Any]) -> Dict[str, Any]:
        """Execute a tool call"""
        try:
            if tool_name == "hello_world":
                name = params.get("name", "World")
                return {{
                    "success": True,
                    "result": f"Hello, {{name}}! 👋"
                }}
            
            elif tool_name == "echo":
                message = params.get("message", "")
                return {{
                    "success": True,
                    "result": message
                }}
            
            elif tool_name == "calculator":
                op = params.get("operation")
                a = params.get("a", 0)
                b = params.get("b", 0)
                
                if op == "add":
                    result = a + b
                elif op == "subtract":
                    result = a - b
                elif op == "multiply":
                    result = a * b
                elif op == "divide":
                    if b == 0:
                        return {{"success": False, "error": "Division by zero"}}
                    result = a / b
                else:
                    return {{"success": False, "error": f"Unknown operation: {{op}}"}}
                
                return {{
                    "success": True,
                    "result": result
                }}
            
            elif tool_name == "authenticate" and 'auth' in {features}:
                token = params.get("token", "")
                # Simple token validation
                if len(token) >= 10:
                    return {{
                        "success": True,
                        "result": {{"authenticated": True, "user_id": "user_123"}}
                    }}
                return {{"success": False, "error": "Invalid token"}}
            
            elif tool_name == "get_logs" and 'logging' in {features}:
                level = params.get("level", "info")
                limit = params.get("limit", 100)
                return {{
                    "success": True,
                    "result": {{"logs": [], "level": level, "limit": limit}}
                }}
            
            else:
                return {{"success": False, "error": f"Tool not found: {{tool_name}}"}}
                
        except Exception as e:
            return {{"success": False, "error": str(e)}}
    
    def get_manifest(self) -> Dict[str, Any]:
        """Get MCP server manifest"""
        return {{
            "name": self.name,
            "version": self.version,
            "description": "MCP Server generated by MCP Toolkit CLI",
            "tools": self.tools
        }}


def main():
    """Main entry point for stdio MCP communication"""
    server = {project_name.replace('-', '_').title().replace('_', '')}Server()
    
    for line in sys.stdin:
        try:
            request = json.loads(line.strip())
            method = request.get("method")
            params = request.get("params", {{}})
            request_id = request.get("id")
            
            response = {{"jsonrpc": "2.0", "id": request_id}}
            
            if method == "initialize":
                response["result"] = {{
                    "protocolVersion": "2024-11-05",
                    "capabilities": {{}},
                    "serverInfo": {{
                        "name": server.name,
                        "version": server.version
                    }}
                }}
            
            elif method == "tools/list":
                response["result"] = {{"tools": server.tools}}
            
            elif method == "tools/call":
                tool_name = params.get("name")
                tool_params = params.get("arguments", {{}})
                response["result"] = server.call_tool(tool_name, tool_params)
            
            elif method == "manifest":
                response["result"] = server.get_manifest()
            
            else:
                response["error"] = {{
                    "code": -32601,
                    "message": f"Method not found: {{method}}"
                }}
            
            print(json.dumps(response), flush=True)
            
        except json.JSONDecodeError:
            print(json.dumps({{
                "jsonrpc": "2.0",
                "error": {{"code": -32700, "message": "Parse error"}}
            }}), flush=True)
        except Exception as e:
            print(json.dumps({{
                "jsonrpc": "2.0",
                "error": {{"code": -32603, "message": str(e)}}
            }}), flush=True)


if __name__ == '__main__':
    main()
'''

    # Manifest file
    manifest = {
        "name": project_name,
        "version": "1.0.0",
        "description": f"MCP Server - {project_name}",
        "author": "",
        "license": "MIT",
        "tools": [
            {
                "name": "hello_world",
                "description": "Say hello to the world"
            },
            {
                "name": "echo",
                "description": "Echo back the input message"
            },
            {
                "name": "calculator",
                "description": "Perform basic calculations"
            }
        ],
        "features": features
    }
    
    # README
    readme = f'''# {project_name}

MCP Server generated by MCP Toolkit CLI

## Quick Start

```bash
# Install dependencies
pip install -r requirements.txt

# Run the server
python server.py

# Or use MCP Toolkit CLI
mcp-toolkit validate .
mcp-toolkit test .
```

## Tools

- **hello_world** - Say hello to the world
- **echo** - Echo back the input message
- **calculator** - Perform basic calculations

## Features

{chr(10).join([f"- {f}" for f in features]) if features else "- Basic MCP server"}

## License

MIT
'''

    # Requirements
    requirements = "# MCP Server Dependencies\n# No external dependencies required (zero-dependency core)\n"
    if 'auth' in features:
        requirements += "\n# Optional: For JWT auth support\n# PyJWT>=2.0.0\n"
    if 'metrics' in features:
        requirements += "\n# Optional: For metrics collection\n# prometheus-client>=0.15.0\n"

    # Config
    config = {
        "server": {
            "name": project_name,
            "version": "1.0.0",
            "host": "0.0.0.0",
            "port": 8080
        },
        "features": features,
        "logging": {
            "level": "info",
            "format": "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        }
    }

    # .gitignore
    gitignore = '''# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
venv/
ENV/
env/

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Logs
*.log
logs/

# Environment variables
.env
.env.local
'''

    files = {
        'server.py': server_py,
        'mcp_manifest.json': json.dumps(manifest, indent=2),
        'README.md': readme,
        'requirements.txt': requirements,
        'config.json': json.dumps(config, indent=2),
        '.gitignore': gitignore
    }
    
    return files


def _get_typescript_files(template, project_name, features):
    """Generate TypeScript template files"""
    
    package_json = {
        "name": project_name,
        "version": "1.0.0",
        "description": f"MCP Server - {project_name}",
        "main": "dist/server.js",
        "scripts": {
            "build": "tsc",
            "start": "node dist/server.js",
            "dev": "ts-node src/server.ts"
        },
        "dependencies": {},
        "devDependencies": {
            "typescript": "^5.0.0",
            "@types/node": "^20.0.0",
            "ts-node": "^10.9.0"
        }
    }
    
    server_ts = f'''import {{ MCPServer }} from './types';

class {project_name.replace('-', '').title()}Server implements MCPServer {{
    name = "{project_name}";
    version = "1.0.0";
    
    tools = [
        {{
            name: "hello_world",
            description: "Say hello to the world",
            parameters: {{
                type: "object",
                properties: {{
                    name: {{ type: "string" }}
                }}
            }}
        }},
        {{
            name: "echo",
            description: "Echo back the input message",
            parameters: {{
                type: "object",
                properties: {{
                    message: {{ type: "string" }}
                }},
                required: ["message"]
            }}
        }}
    ];
    
    async callTool(name: string, params: any): Promise<any> {{
        switch(name) {{
            case "hello_world":
                return {{ success: true, result: `Hello, ${{params.name || 'World'}}! 👋` }};
            case "echo":
                return {{ success: true, result: params.message }};
            default:
                return {{ success: false, error: `Tool not found: ${{name}}` }};
        }}
    }}
}}

const server = new {project_name.replace('-', '').title()}Server();

// Stdio MCP communication
process.stdin.on('data', (data) => {{
    try {{
        const request = JSON.parse(data.toString().trim());
        const {{ method, params, id }} = request;
        
        let result: any;
        
        if (method === 'initialize') {{
            result = {{
                protocolVersion: '2024-11-05',
                serverInfo: {{ name: server.name, version: server.version }}
            }};
        }} else if (method === 'tools/list') {{
            result = {{ tools: server.tools }};
        }} else if (method === 'tools/call') {{
            result = server.callTool(params.name, params.arguments);
        }} else {{
            result = {{ error: {{ code: -32601, message: `Method not found: ${{method}}` }} }};
        }}
        
        console.log(JSON.stringify({{ jsonrpc: '2.0', id, result }}));
    }} catch (e) {{
        console.log(JSON.stringify({{ jsonrpc: '2.0', error: {{ code: -32700, message: 'Parse error' }} }}));
    }}
}});
'''

    tsconfig = {
        "compilerOptions": {
            "target": "ES2020",
            "module": "commonjs",
            "outDir": "./dist",
            "rootDir": "./src",
            "strict": True,
            "esModuleInterop": True
        },
        "include": ["src/**/*"]
    }

    files = {
        'src/server.ts': server_ts,
        'src/types.ts': 'export interface MCPServer {\n  name: string;\n  version: string;\n  tools: any[];\n  callTool(name: string, params: any): Promise<any>;\n}\n',
        'package.json': json.dumps(package_json, indent=2),
        'tsconfig.json': json.dumps(tsconfig, indent=2),
        'README.md': f'# {project_name}\n\nMCP Server (TypeScript)\n'
    }
    
    return files


def _get_javascript_files(template, project_name, features):
    """Generate JavaScript template files"""
    
    package_json = {
        "name": project_name,
        "version": "1.0.0",
        "description": f"MCP Server - {project_name}",
        "main": "server.js",
        "scripts": {
            "start": "node server.js"
        },
        "dependencies": {}
    }
    
    server_js = f'''class {project_name.replace('-', '').title()}Server {{
    constructor() {{
        this.name = "{project_name}";
        this.version = "1.0.0";
        this.tools = [
            {{
                name: "hello_world",
                description: "Say hello to the world",
                parameters: {{
                    type: "object",
                    properties: {{
                        name: {{ type: "string" }}
                    }}
                }}
            }},
            {{
                name: "echo",
                description: "Echo back the input message",
                parameters: {{
                    type: "object",
                    properties: {{
                        message: {{ type: "string" }}
                    }},
                    required: ["message"]
                }}
            }}
        ];
    }}
    
    async callTool(name, params) {{
        switch(name) {{
            case "hello_world":
                return {{ success: true, result: `Hello, ${{params.name || 'World'}}! 👋` }};
            case "echo":
                return {{ success: true, result: params.message }};
            default:
                return {{ success: false, error: `Tool not found: ${{name}}` }};
        }}
    }}
}}

const server = new {project_name.replace('-', '').title()}Server();

process.stdin.on('data', (data) => {{
    try {{
        const request = JSON.parse(data.toString().trim());
        const {{ method, params, id }} = request;
        
        let result;
        
        if (method === 'initialize') {{
            result = {{
                protocolVersion: '2024-11-05',
                serverInfo: {{ name: server.name, version: server.version }}
            }};
        }} else if (method === 'tools/list') {{
            result = {{ tools: server.tools }};
        }} else if (method === 'tools/call') {{
            result = server.callTool(params.name, params.arguments);
        }} else {{
            result = {{ error: {{ code: -32601, message: `Method not found: ${{method}}` }} }};
        }}
        
        console.log(JSON.stringify({{ jsonrpc: '2.0', id, result }}));
    }} catch (e) {{
        console.log(JSON.stringify({{ jsonrpc: '2.0', error: {{ code: -32700, message: 'Parse error' }} }}));
    }}
}});
'''

    files = {
        'server.js': server_js,
        'package.json': json.dumps(package_json, indent=2),
        'README.md': f'# {project_name}\n\nMCP Server (JavaScript)\n'
    }
    
    return files
